#!/bin/sh

alls="allinclude.builtin.md"
> "$alls"

rm -f ./$alls

for file in *.h; do
    [ -e "$file" ] || continue
    [ -L "$file" ] && continue
    [ -f "$file" ] || continue
    filename="$file"
    if content=$(cat "$file" 2>/dev/null); then
        cat >> "$alls" <<EOF
\`\`\`$filename
$content
\`\`\`

EOF
    fi
done

chown mobile:mobile $alls
echo "yes, path: $alls"